### PR TITLE
x64 build fixes

### PR DESCRIPTION
**Pull request by moradin**

### CODE REVIEW

**Comment by fancycode** [comment]
Please avoid unnecessary whitespace changes. Your change seems to change all the indentation...

**Comment by fancycode** [comment]
Besides: what x64 build error does this fix? The CI runners test compilation on both 32 and 64bit platforms.

**Comment by moradin** [comment]
Sorry I should have been more clear, I'm compiling with warnings as errors and it fixes warnings.

**Comment by moradin** [comment]
Fixed the whitespaces but some tabs were already used before so for the sake of consistency changed those to spaces too

**Comment by clshack** [comment]
I am using this library on vs2015 with 64bit without problems, what do these fixes ?

**Comment by moradin** [comment]
They fix warnings in the compilation

**Comment by fancycode** [comment]
The changes break both the CI testers, so I won't merge unless they are green again.

**Pull request closed without merging**
